version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
